/*
 * Created on 22 nov. 2013 ( Time 16:27:33 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Author ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.AuthorPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Author" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AuthorPersistenceJPA extends GenericJpaService<Author, Integer> implements AuthorPersistence {

	/**
	 * Constructor
	 */
	public AuthorPersistenceJPA() {
		super(Author.class);
	}

	/**
	 * Delete author.
	 */
	public boolean delete(Author author) {
		return delete(author.getId());
	}

}
