/*
 * Created on 21 nov. 2013 ( Time 15:35:36 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Author ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.AuthorPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Author" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class AuthorPersistenceJPA extends GenericJpaService<Author, Integer> implements AuthorPersistence {

	/**
	 * Constructor
	 */
	public AuthorPersistenceJPA() {
		super(Author.class);
	}

	public Author load( int id ) {
		return super.load( id );
	}

	public boolean delete( int id ) {
		return super.delete( id );
	}

	public boolean delete(Author entity) {
		if ( entity != null ) {
			return super.delete( entity.getId() );
		}
		return false ;
	}

}
