/*
 * Created on 22 nov. 2013 ( Time 16:27:37 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Book ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.BookPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Book" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookPersistenceJPA extends GenericJpaService<Book, Integer> implements BookPersistence {

	/**
	 * Constructor
	 */
	public BookPersistenceJPA() {
		super(Book.class);
	}

	/**
	 * Delete book.
	 */
	public boolean delete(Book book) {
		return delete(book.getId());
	}

}
