/*
 * Created on 22 nov. 2013 ( Time 16:27:38 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.BookOrder ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.BookOrderPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "BookOrder" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderPersistenceJPA extends GenericJpaService<BookOrder, Integer> implements BookOrderPersistence {

	/**
	 * Constructor
	 */
	public BookOrderPersistenceJPA() {
		super(BookOrder.class);
	}

	/**
	 * Delete bookorder.
	 */
	public boolean delete(BookOrder bookorder) {
		return delete(bookorder.getId());
	}

}
