/*
 * Created on 22 nov. 2013 ( Time 16:27:40 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.BookOrderItem ;
import org.telosys.starterkits.bean.BookOrderItemId ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.BookOrderItemPersistence;

import org.telosys.starterkits.bean.BookOrderItemId;
/**
 * JPA implementation for basic persistence operations ( entity "BookOrderItem" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class BookOrderItemPersistenceJPA extends GenericJpaService<BookOrderItem, BookOrderItemId> implements BookOrderItemPersistence {

	/**
	 * Constructor
	 */
	public BookOrderItemPersistenceJPA() {
		super(BookOrderItem.class);
	}

	/**
	 * Delete bookorderitem.
	 */
	public boolean delete(BookOrderItem bookorderitem) {
		return delete(bookorderitem.getId());
	}

}
