/*
 * Created on 22 nov. 2013 ( Time 16:27:42 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Country ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.CountryPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Country" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class CountryPersistenceJPA extends GenericJpaService<Country, String> implements CountryPersistence {

	/**
	 * Constructor
	 */
	public CountryPersistenceJPA() {
		super(Country.class);
	}

	/**
	 * Delete country.
	 */
	public boolean delete(Country country) {
		return delete(country.getCode());
	}

}
