/*
 * Created on 22 nov. 2013 ( Time 16:27:48 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.EmployeeGroup ;
import org.telosys.starterkits.bean.EmployeeGroupId ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.EmployeeGroupPersistence;

import org.telosys.starterkits.bean.EmployeeGroupId;
/**
 * JPA implementation for basic persistence operations ( entity "EmployeeGroup" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class EmployeeGroupPersistenceJPA extends GenericJpaService<EmployeeGroup, EmployeeGroupId> implements EmployeeGroupPersistence {

	/**
	 * Constructor
	 */
	public EmployeeGroupPersistenceJPA() {
		super(EmployeeGroup.class);
	}

	/**
	 * Delete employeegroup.
	 */
	public boolean delete(EmployeeGroup employeegroup) {
		return delete(employeegroup.getId());
	}

}
