/*
 * Created on 22 nov. 2013 ( Time 16:27:47 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Employee ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.EmployeePersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Employee" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class EmployeePersistenceJPA extends GenericJpaService<Employee, String> implements EmployeePersistence {

	/**
	 * Constructor
	 */
	public EmployeePersistenceJPA() {
		super(Employee.class);
	}

	/**
	 * Delete employee.
	 */
	public boolean delete(Employee employee) {
		return delete(employee.getCode());
	}

}
