/*
 * Created on 22 nov. 2013 ( Time 16:27:51 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Publisher ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.PublisherPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Publisher" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class PublisherPersistenceJPA extends GenericJpaService<Publisher, Integer> implements PublisherPersistence {

	/**
	 * Constructor
	 */
	public PublisherPersistenceJPA() {
		super(Publisher.class);
	}

	/**
	 * Delete publisher.
	 */
	public boolean delete(Publisher publisher) {
		return delete(publisher.getCode());
	}

}
