/*
 * Created on 22 nov. 2013 ( Time 16:27:53 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Review ;
import org.telosys.starterkits.bean.ReviewId ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.ReviewPersistence;

import org.telosys.starterkits.bean.ReviewId;
/**
 * JPA implementation for basic persistence operations ( entity "Review" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ReviewPersistenceJPA extends GenericJpaService<Review, ReviewId> implements ReviewPersistence {

	/**
	 * Constructor
	 */
	public ReviewPersistenceJPA() {
		super(Review.class);
	}

	/**
	 * Delete review.
	 */
	public boolean delete(Review review) {
		return delete(review.getId());
	}

}
