/*
 * Created on 22 nov. 2013 ( Time 16:27:54 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Shop ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.ShopPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Shop" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class ShopPersistenceJPA extends GenericJpaService<Shop, String> implements ShopPersistence {

	/**
	 * Constructor
	 */
	public ShopPersistenceJPA() {
		super(Shop.class);
	}

	/**
	 * Delete shop.
	 */
	public boolean delete(Shop shop) {
		return delete(shop.getCode());
	}

}
