/*
 * Created on 22 nov. 2013 ( Time 16:27:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Synopsis ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.SynopsisPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Synopsis" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class SynopsisPersistenceJPA extends GenericJpaService<Synopsis, Integer> implements SynopsisPersistence {

	/**
	 * Constructor
	 */
	public SynopsisPersistenceJPA() {
		super(Synopsis.class);
	}

	/**
	 * Delete synopsis.
	 */
	public boolean delete(Synopsis synopsis) {
		return delete(synopsis.getBookId());
	}

}
