/*
 * Created on 22 nov. 2013 ( Time 16:27:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */

package org.telosys.starterkits.persistence.services.jpa;


import org.telosys.starterkits.bean.Workgroup ;
import org.telosys.starterkits.persistence.commons.jpa.GenericJpaService;
import org.telosys.starterkits.persistence.services.WorkgroupPersistence;

/**
 * JPA implementation for basic persistence operations ( entity "Workgroup" )
 * 
 * @author Telosys Tools Generator
 *
 */
public class WorkgroupPersistenceJPA extends GenericJpaService<Workgroup, Short> implements WorkgroupPersistence {

	/**
	 * Constructor
	 */
	public WorkgroupPersistenceJPA() {
		super(Workgroup.class);
	}

	/**
	 * Delete workgroup.
	 */
	public boolean delete(Workgroup workgroup) {
		return delete(workgroup.getId());
	}

}
