/*
 * Created on 6 déc. 2013 ( Time 18:15:30 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;


/**
 * Composite primary key for entity "BookOrderItem" ( stored in table "book_order_item" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class BookOrderItemId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="book_id", nullable=false)
    private Integer bookId ;
    
    @Column(name="book_order_id", nullable=false)
    private Integer bookOrderId ;
    
    public BookOrderItemId()
    {
        super();
    }

    public BookOrderItemId( int bookId, int bookOrderId )
    {
        super();
        this.bookId = bookId ;
        this.bookOrderId = bookOrderId ;
    }
    
    public void setBookId( Integer value )
    {
        this.bookId = value;
    }

    public Integer getBookId()
    {
        return this.bookId;
    }

    public void setBookOrderId( Integer value )
    {
        this.bookOrderId = value;
    }

    public Integer getBookOrderId()
    {
        return this.bookOrderId;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(bookId); 
		sb.append("|"); 
		sb.append(bookOrderId); 
        return sb.toString();
    }

	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		BookOrderItemId other = (BookOrderItemId) obj; 
		//--- Attribute bookId
		if ( bookId != other.bookId ) return false ; 
		//--- Attribute bookOrderId
		if ( bookOrderId != other.bookOrderId ) return false ; 
		return true; 
	} 

	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute bookId
		result = prime * result + bookId;
		//--- Attribute bookOrderId
		result = prime * result + bookOrderId;
		
		return result; 
	} 

}
