/*
 * Created on 22 nov. 2013 ( Time 16:27:53 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.persistence.services;

import java.util.List;
import java.util.Map;

import org.telosys.starterkits.bean.Review ;

import org.telosys.starterkits.bean.ReviewId;

/**
 * Basic persistence operations for entity "Review"
 * 
 * This Bean has a composite Primary Key : ReviewId
 *
 * @author Telosys Tools Generator
 *
 */
public interface ReviewPersistence {

	/**
	 * Deletes the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param review
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(Review review) ;

	/**
	 * Deletes the entity by its Primary Key <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param id
	 * @return true if found and deleted, false if not found
	 */
	public boolean delete(ReviewId id) ;

	/**
	 * Inserts the given entity and commit <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param review
	 */
	public void insert(Review review) ;

	/**
	 * Loads the entity for the given Primary Key <br>
	 * @param id
	 * @return the entity loaded (or null if not found)
	 */
	public Review load(ReviewId id) ;

	/**
	 * Loads ALL the entities (use with caution)
	 * @return
	 */
	public List<Review> loadAll() ;

	/**
	 * Loads a list of entities using the given "named query" without parameter 
	 * @param queryName
	 * @return
	 */
	public List<Review> loadByNamedQuery(String queryName) ;

	/**
	 * Loads a list of entities using the given "named query" with parameters 
	 * @param queryName
	 * @param queryParameters
	 * @return
	 */
	public List<Review> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) ;

	/**
	 * Saves (create or update) the given entity <br>
	 * Transactional operation ( begin transaction and commit )
	 * @param review
	 * @return
	 */
	public Review save(Review review) ;

	/**
	 * Search the entities matching the given search criteria
	 * @param criteria
	 * @return
	 */
	public List<Review> search( Map<String, Object> criteria ) ;
}
