/*
 * Created on 22 nov. 2013 ( Time 16:55:23 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.bean;
// This Bean has a basic Primary Key (not composite) 

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "BOOK_ORDER"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="BOOK_ORDER", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="BookOrder.query1", query="SELECT x FROM BookOrder x WHERE  " ),
//  @NamedQuery ( name="BookOrder.query2", query="SELECT x FROM BookOrder x WHERE  " )
// } )
public class BookOrder implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer id;

    @Column(name="SHOP_CODE", nullable=false, length=3)
    private String shopCode ;

    @Column(name="CUSTOMER_CODE", nullable=false, length=5)
    private String customerCode ;

    @Column(name="EMPLOYEE_CODE", nullable=false, length=4)
    private String employeeCode ;

    @Temporal(TemporalType.DATE)
    @Column(name="DATE")
    private Date date ;

    @Column(name="STATE")
    private Integer state ;

	public Integer getId() {
        return id;
    }
 
    public void setId(Integer id) {
        this.id = id;
    }

    public void setShopCode( String shopCode )
    {
        this.shopCode = shopCode;
    }

    public String getShopCode()
    {
        return this.shopCode;
    }

    public void setCustomerCode( String customerCode )
    {
        this.customerCode = customerCode;
    }

    public String getCustomerCode()
    {
        return this.customerCode;
    }

    public void setEmployeeCode( String employeeCode )
    {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeCode()
    {
        return this.employeeCode;
    }

    public void setDate( Date date )
    {
        this.date = date;
    }

    public Date getDate()
    {
        return this.date;
    }

    public void setState( Integer state )
    {
        this.state = state;
    }

    public Integer getState()
    {
        return this.state;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(date); 
        sb.append( "|" ); 
        sb.append(state); 
        return sb.toString(); 
    }

}
