/*
 * Created on 29 nov. 2013 ( Time 17:32:10 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "BookOrderItem" ( stored in table "BOOK_ORDER_ITEM" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class BookOrderItemId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="BOOK_ORDER_ID", nullable=false)
    private int bookOrderId ;
    
    @Column(name="BOOK_ID", nullable=false)
    private int bookId ;
    
    public BookOrderItemId()
    {
        super();
    }

    public BookOrderItemId( int bookOrderId, int bookId )
    {
        super();
        this.bookOrderId = bookOrderId ;
        this.bookId = bookId ;
    }
    
    public void setBookOrderId( int value )
    {
        this.bookOrderId = value;
    }

    public int getBookOrderId()
    {
        return this.bookOrderId;
    }

    public void setBookId( int value )
    {
        this.bookId = value;
    }

    public int getBookId()
    {
        return this.bookId;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(bookOrderId); 
		sb.append("|"); 
		sb.append(bookId); 
        return sb.toString();
    }

}
