/*
 * Created on 30 déc. 2013 ( Time 14:44:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package org.telosys.starterkits.bean;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "BookOrderItem" ( stored in table "book_order_item" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class BookOrderItemId implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="book_id", nullable=false)
    private int        bookId       ;
    
    @Column(name="book_order_id", nullable=false)
    private int        bookOrderId  ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public BookOrderItemId()
    {
        super();
    }

    public BookOrderItemId( int bookId, int bookOrderId )
    {
        super();
        this.bookId = bookId ;
        this.bookOrderId = bookOrderId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setBookId( int value )
    {
        this.bookId = value;
    }
    public int getBookId()
    {
        return this.bookId;
    }

    public void setBookOrderId( int value )
    {
        this.bookOrderId = value;
    }
    public int getBookOrderId()
    {
        return this.bookOrderId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		BookOrderItemId other = (BookOrderItemId) obj; 
		//--- Attribute bookId
		if ( bookId != other.bookId ) return false ; 
		//--- Attribute bookOrderId
		if ( bookOrderId != other.bookOrderId ) return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute bookId
		result = prime * result + bookId;
		//--- Attribute bookOrderId
		result = prime * result + bookOrderId;
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(bookId); 
		sb.append("|"); 
		sb.append(bookOrderId); 
        return sb.toString();
    }
}
