/*
 * Created on 6 déc. 2013 ( Time 15:33:19 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
// This Bean has a basic Primary Key (not composite) 
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;
import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "book_order"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="book_order", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="BookOrder.query1", query="SELECT x FROM BookOrder x WHERE  " ),
//  @NamedQuery ( name="BookOrder.query2", query="SELECT x FROM BookOrder x WHERE  " )
// } )
public class BookOrder implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name="id", nullable=false)

    private Integer id;

    @Temporal(TemporalType.DATE)
    @Column(name="date")

    private Date date ;

    @Column(name="state")

    private Integer state ;

    @Column(name="customer_code", length=5)
    @Size( max = 5 )
    private String customerCode ;

    @Column(name="employee_code", length=4)
    @Size( max = 4 )
    private String employeeCode ;

    @Column(name="shop_code", length=3)
    @Size( max = 3 )
    private String shopCode ;

	public Integer getId() {
        return id;
    }
 
    public void setId(Integer id) {
        this.id = id;
    }

    public void setDate( Date date )
    {
        this.date = date;
    }

    public Date getDate()
    {
        return this.date;
    }

    public void setState( Integer state )
    {
        this.state = state;
    }

    public Integer getState()
    {
        return this.state;
    }

    public void setCustomerCode( String customerCode )
    {
        this.customerCode = customerCode;
    }

    public String getCustomerCode()
    {
        return this.customerCode;
    }

    public void setEmployeeCode( String employeeCode )
    {
        this.employeeCode = employeeCode;
    }

    public String getEmployeeCode()
    {
        return this.employeeCode;
    }

    public void setShopCode( String shopCode )
    {
        this.shopCode = shopCode;
    }

    public String getShopCode()
    {
        return this.shopCode;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(date); 
        sb.append( "|" ); 
        sb.append(state); 
        sb.append( "|" ); 
        sb.append(customerCode); 
        sb.append( "|" ); 
        sb.append(employeeCode); 
        sb.append( "|" ); 
        sb.append(shopCode); 
        return sb.toString(); 
    }

}
