/*
 * Created on 29 nov. 2013 ( Time 17:32:08 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
// This Bean has a basic Primary Key (not composite) 
package org.telosys.starterkits.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.math.BigDecimal;

import java.util.List;
import javax.persistence.*;
import javax.validation.Valid;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "BOOK"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="BOOK", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Book.query1", query="SELECT x FROM Book x WHERE  " ),
//  @NamedQuery ( name="Book.query2", query="SELECT x FROM Book x WHERE  " )
// } )
public class Book implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer id;

    @Column(name="ISBN", nullable=false, length=13)
    private String isbn ;

    @Column(name="TITLE", length=160)
    private String title ;

    @Column(name="PRICE")
    private BigDecimal price ;

    @Column(name="QUANTITY")
    private Integer quantity ;

    @Column(name="DISCOUNT")
    private Integer discount ;

    @Column(name="AVAILABILITY")
    private Short availability ;

    @Column(name="BEST_SELLER")
    private Short bestSeller ;

    @ManyToOne
    @JoinColumn(name="AUTHOR_ID", referencedColumnName="ID", insertable=false, updatable=false)
    private Author author;

    @ManyToOne
    @JoinColumn(name="PUBLISHER_ID", referencedColumnName="CODE", insertable=false, updatable=false)
    private Publisher publisher;

	public Integer getId() {
        return id;
    }
 
    public void setId(Integer id) {
        this.id = id;
    }

    public void setIsbn( String isbn )
    {
        this.isbn = isbn;
    }

    public String getIsbn()
    {
        return this.isbn;
    }

    public void setTitle( String title )
    {
        this.title = title;
    }

    public String getTitle()
    {
        return this.title;
    }

    public void setPrice( BigDecimal price )
    {
        this.price = price;
    }

    public BigDecimal getPrice()
    {
        return this.price;
    }

    public void setQuantity( Integer quantity )
    {
        this.quantity = quantity;
    }

    public Integer getQuantity()
    {
        return this.quantity;
    }

    public void setDiscount( Integer discount )
    {
        this.discount = discount;
    }

    public Integer getDiscount()
    {
        return this.discount;
    }

    public void setAvailability( Short availability )
    {
        this.availability = availability;
    }

    public Short getAvailability()
    {
        return this.availability;
    }

    public void setBestSeller( Short bestSeller )
    {
        this.bestSeller = bestSeller;
    }

    public Short getBestSeller()
    {
        return this.bestSeller;
    }

    public void setAuthor( Author author )
    {
        this.author = author;
    }

    public Author getAuthor()
    {
        return this.author;
    }

    public void setPublisher( Publisher publisher )
    {
        this.publisher = publisher;
    }

    public Publisher getPublisher()
    {
        return this.publisher;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(id); 
        sb.append("|"); 
        sb.append(isbn); 
        sb.append( "|" ); 
        sb.append(title); 
        sb.append( "|" ); 
        sb.append(price); 
        sb.append( "|" ); 
        sb.append(quantity); 
        sb.append( "|" ); 
        sb.append(discount); 
        sb.append( "|" ); 
        sb.append(availability); 
        sb.append( "|" ); 
        sb.append(bestSeller); 
        return sb.toString(); 
    }

}
