/*
 * Created on 20 nov. 2013 ( Time 15:32:39 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 

package org.telosys.starterkits.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "COUNTRY"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="COUNTRY", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Country.query1", query="SELECT x FROM Country x WHERE  " ),
//  @NamedQuery ( name="Country.query2", query="SELECT x FROM Country x WHERE  " )
// } )
public class Country implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="CODE", nullable=false, length=2)
    private String code ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="NAME", length=45)
    private String name ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
//    @OneToMany(mappedBy="country", targetEntity=Customer.class)
//    private List<Customer> listOfCustomer;

//    @OneToMany(mappedBy="country", targetEntity=Publisher.class)
//    private List<Publisher> listOfPublisher;

//    @OneToMany(mappedBy="country", targetEntity=Shop.class)
//    private List<Shop> listOfShop  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Country()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code )
    {
        this.code = code ;
    }
    public String getCode()
    {
        return this.code;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : NAME ( VARCHAR ) 
    public void setName( String name )
    {
        this.name = name;
    }
    public String getName()
    {
        return this.name;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
//    @XmlTransient
//    public void setListOfCustomer( List<Customer> listOfCustomer )
//    {
//        this.listOfCustomer = listOfCustomer;
//    }
//    public List<Customer> getListOfCustomer()
//    {
//        return this.listOfCustomer;
//    }

//    @XmlTransient
//    public void setListOfPublisher( List<Publisher> listOfPublisher )
//    {
//        this.listOfPublisher = listOfPublisher;
//    }
//    public List<Publisher> getListOfPublisher()
//    {
//        return this.listOfPublisher;
//    }

//    @XmlTransient
//    public void setListOfShop( List<Shop> listOfShop )
//    {
//        this.listOfShop = listOfShop;
//    }
//    public List<Shop> getListOfShop()
//    {
//        return this.listOfShop;
//    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(name); 
        return sb.toString(); 
    }

}
