/*
 * Created on 6 déc. 2013 ( Time 15:33:21 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "EmployeeGroup" ( stored in table "employee_group" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class EmployeeGroupId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="employee_code", nullable=false, length=4)
    private String employeeCode ;
    
    @Column(name="group_id", nullable=false)
    private Short groupId ;
    
    public EmployeeGroupId()
    {
        super();
    }

    public EmployeeGroupId( String employeeCode, short groupId )
    {
        super();
        this.employeeCode = employeeCode ;
        this.groupId = groupId ;
    }
    
    public void setEmployeeCode( String value )
    {
        this.employeeCode = value;
    }

    public String getEmployeeCode()
    {
        return this.employeeCode;
    }

    public void setGroupId( Short value )
    {
        this.groupId = value;
    }

    public Short getGroupId()
    {
        return this.groupId;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(employeeCode); 
		sb.append("|"); 
		sb.append(groupId); 
        return sb.toString();
    }

}
