/*
 * Created on 6 déc. 2013 ( Time 18:15:30 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;


/**
 * Composite primary key for entity "EmployeeGroup" ( stored in table "employee_group" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class EmployeeGroupId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="employee_code", nullable=false, length=4)
    private String employeeCode ;
    
    @Column(name="group_id", nullable=false)
    private Short groupId ;
    
    public EmployeeGroupId()
    {
        super();
    }

    public EmployeeGroupId( String employeeCode, short groupId )
    {
        super();
        this.employeeCode = employeeCode ;
        this.groupId = groupId ;
    }
    
    public void setEmployeeCode( String value )
    {
        this.employeeCode = value;
    }

    public String getEmployeeCode()
    {
        return this.employeeCode;
    }

    public void setGroupId( Short value )
    {
        this.groupId = value;
    }

    public Short getGroupId()
    {
        return this.groupId;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(employeeCode); 
		sb.append("|"); 
		sb.append(groupId); 
        return sb.toString();
    }

	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		EmployeeGroupId other = (EmployeeGroupId) obj; 
		//--- Attribute employeeCode
		if ( employeeCode == null ) { 
			if ( other.employeeCode != null ) 
				return false ; 
		} else if ( ! employeeCode.equals(other.employeeCode) ) 
			return false ; 
		//--- Attribute groupId
		if ( groupId != other.groupId ) return false ; 
		return true; 
	} 

	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute employeeCode
		result = prime * result + ((employeeCode == null) ? 0 : employeeCode.hashCode() ) ; 
		//--- Attribute groupId
		result = prime * result + groupId;
		
		return result; 
	} 

}
