/*
 * Created on 22 nov. 2013 ( Time 16:55:25 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.bean;
// This Bean has a basic Primary Key (not composite) 

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "EMPLOYEE"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="EMPLOYEE", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Employee.query1", query="SELECT x FROM Employee x WHERE  " ),
//  @NamedQuery ( name="Employee.query2", query="SELECT x FROM Employee x WHERE  " )
// } )
public class Employee implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name="CODE", nullable=false, length=4)
    private String code;

    @Column(name="SHOP_CODE", nullable=false, length=3)
    private String shopCode ;

    @Column(name="FIRST_NAME", length=40)
    private String firstName ;

    @Column(name="LAST_NAME", nullable=false, length=40)
    private String lastName ;

    @Column(name="MANAGER")
    private Short manager ;

    @Column(name="BADGE_NUMBER")
    private Integer badgeNumber ;

    @Column(name="EMAIL", length=320)
    private String email ;

	public String getCode() {
        return code;
    }
 
    public void setCode(String code) {
        this.code = code;
    }

    public void setShopCode( String shopCode )
    {
        this.shopCode = shopCode;
    }

    public String getShopCode()
    {
        return this.shopCode;
    }

    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }

    public String getFirstName()
    {
        return this.firstName;
    }

    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }

    public String getLastName()
    {
        return this.lastName;
    }

    public void setManager( Short manager )
    {
        this.manager = manager;
    }

    public Short getManager()
    {
        return this.manager;
    }

    public void setBadgeNumber( Integer badgeNumber )
    {
        this.badgeNumber = badgeNumber;
    }

    public Integer getBadgeNumber()
    {
        return this.badgeNumber;
    }

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getEmail()
    {
        return this.email;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(firstName); 
        sb.append( "|" ); 
        sb.append(lastName); 
        sb.append( "|" ); 
        sb.append(manager); 
        sb.append( "|" ); 
        sb.append(email); 
        return sb.toString(); 
    }

}
