/*
 * Created on 30 déc. 2013 ( Time 14:44:47 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 
/******
keyAttributes size = 1
nonKeyAttributes size = 6
bigList size = 7
. code - String
. email - String
. firstName - String
. lastName - String
. manager - Short
. badgeNumber - Integer
. shopCode - String
******/
package org.telosys.starterkits.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.List;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "employee"
 *
 * @author Telosys Tools Generator
 *
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="employee", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Employee.query1", query="SELECT x FROM Employee x WHERE  " ),
//  @NamedQuery ( name="Employee.query2", query="SELECT x FROM Employee x WHERE  " )
// } )
public class Employee implements Serializable
{
    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="code", nullable=false, length=4)
    private String     code         ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="email", length=320)
    private String     email        ;

    @Column(name="first_name", length=40)
    private String     firstName    ;

    @Column(name="last_name", nullable=false, length=40)
    private String     lastName     ;

    @Column(name="manager")
    private Short      manager      ;

	// "badgeNumber" (column "badge_number") is not defined by itself because used as FK in a link 
	// "shopCode" (column "shop_code") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="shop_code", referencedColumnName="code")
    private Shop       shop        ;

    @OneToMany(mappedBy="employee", targetEntity=BookOrder.class)
    private List<BookOrder> listOfBookOrder;

    @ManyToOne
    @JoinColumn(name="badge_number", referencedColumnName="badge_number")
    private Badge      badge       ;

    @OneToMany(mappedBy="employee", targetEntity=Shop.class)
    private List<Shop> listOfShop  ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public Employee()
    {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setCode( String code )
    {
        this.code = code ;
    }
    public String getCode()
    {
        return this.code;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : email ( varchar ) 
    public void setEmail( String email )
    {
        this.email = email;
    }
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : first_name ( varchar ) 
    public void setFirstName( String firstName )
    {
        this.firstName = firstName;
    }
    public String getFirstName()
    {
        return this.firstName;
    }

    //--- DATABASE MAPPING : last_name ( varchar ) 
    public void setLastName( String lastName )
    {
        this.lastName = lastName;
    }
    public String getLastName()
    {
        return this.lastName;
    }

    //--- DATABASE MAPPING : manager ( int2 ) 
    public void setManager( Short manager )
    {
        this.manager = manager;
    }
    public Short getManager()
    {
        return this.manager;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setShop( Shop shop )
    {
        this.shop = shop;
    }
    public Shop getShop()
    {
        return this.shop;
    }

    @XmlTransient
    public void setListOfBookOrder( List<BookOrder> listOfBookOrder )
    {
        this.listOfBookOrder = listOfBookOrder;
    }
    public List<BookOrder> getListOfBookOrder()
    {
        return this.listOfBookOrder;
    }

    public void setBadge( Badge badge )
    {
        this.badge = badge;
    }
    public Badge getBadge()
    {
        return this.badge;
    }

    @XmlTransient
    public void setListOfShop( List<Shop> listOfShop )
    {
        this.listOfShop = listOfShop;
    }
    public List<Shop> getListOfShop()
    {
        return this.listOfShop;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(email); 
        sb.append( "|" ); 
        sb.append(firstName); 
        sb.append( "|" ); 
        sb.append(lastName); 
        sb.append( "|" ); 
        sb.append(manager); 
        return sb.toString(); 
    }

}
