/*
 * Created on 28 nov. 2013 ( Time 10:04:33 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "Review" ( stored in table "REVIEW" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class ReviewId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="CUSTOMER_CODE", nullable=false, length=5)
    private String customerCode ;
    
    @Column(name="BOOK_ID", nullable=false)
    private int bookId ;
    
    public ReviewId()
    {
        super();
    }

    public ReviewId( String customerCode, int bookId )
    {
        super();
        this.customerCode = customerCode ;
        this.bookId = bookId ;
    }
    
    public void setCustomerCode( String value )
    {
        this.customerCode = value;
    }

    public String getCustomerCode()
    {
        return this.customerCode;
    }

    public void setBookId( int value )
    {
        this.bookId = value;
    }

    public int getBookId()
    {
        return this.bookId;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(customerCode); 
		sb.append("|"); 
		sb.append(bookId); 
        return sb.toString();
    }

}
