/*
 * Created on 6 déc. 2013 ( Time 15:33:22 )
 * Generated by Telosys Tools Generator ( version 2.0.7 )
 */
package org.telosys.starterkits.bean;

import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "Review" ( stored in table "review" )
 *
 * @author Telosys Tools Generator
 *
 */
@Embeddable
public class ReviewId implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Column(name="book_id", nullable=false)
    private Integer bookId ;
    
    @Column(name="customer_code", nullable=false, length=5)
    private String customerCode ;
    
    public ReviewId()
    {
        super();
    }

    public ReviewId( int bookId, String customerCode )
    {
        super();
        this.bookId = bookId ;
        this.customerCode = customerCode ;
    }
    
    public void setBookId( Integer value )
    {
        this.bookId = value;
    }

    public Integer getBookId()
    {
        return this.bookId;
    }

    public void setCustomerCode( String value )
    {
        this.customerCode = value;
    }

    public String getCustomerCode()
    {
        return this.customerCode;
    }

    public String toString()
    {
		StringBuffer sb = new StringBuffer(); 
		sb.append(bookId); 
		sb.append("|"); 
		sb.append(customerCode); 
        return sb.toString();
    }

}
