/*
 * Created on 22 nov. 2013 ( Time 17:59:59 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
// This Bean has a basic Primary Key (not composite) 
package org.telosys.starterkits.bean;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import java.util.List;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 * Persistent class for entity stored in table "SHOP"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="SHOP", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Shop.query1", query="SELECT x FROM Shop x WHERE  " ),
//  @NamedQuery ( name="Shop.query2", query="SELECT x FROM Shop x WHERE  " )
// } )
public class Shop implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name="CODE", nullable=false, length=3)
    private String code;

    @Column(name="NAME", length=80)
    private String name ;

    @Column(name="ADDRESS_1", length=80)
    private String address1 ;

    @Column(name="ADDRESS_2", length=80)
    private String address2 ;

    @Column(name="ZIP_CODE")
    private Integer zipCode ;

    @Column(name="CITY", length=45)
    private String city ;

    @Column(name="PHONE", length=14)
    private String phone ;

    @Column(name="EMAIL", length=50)
    private String email ;

	// "countryCode" (column "COUNTRY_CODE") is not defined by itself because used as FK in a link 

	// "executive" (column "EXECUTIVE") is not defined by itself because used as FK in a link 

    @ManyToOne
    @JoinColumn(name="EXECUTIVE", referencedColumnName="CODE", insertable=false, updatable=false)
    private Employee employee;

    @OneToMany(mappedBy="shop", targetEntity=BookOrder.class)
    private List<BookOrder> listOfBookOrder;

    @OneToMany(mappedBy="shop", targetEntity=Employee.class)
    private List<Employee> listOfEmployee;

    @ManyToOne
    @JoinColumn(name="COUNTRY_CODE", referencedColumnName="CODE", insertable=false, updatable=false)
    private Country country;

	public String getCode() {
        return code;
    }
 
    public void setCode(String code) {
        this.code = code;
    }

    public void setName( String name )
    {
        this.name = name;
    }

    public String getName()
    {
        return this.name;
    }

    public void setAddress1( String address1 )
    {
        this.address1 = address1;
    }

    public String getAddress1()
    {
        return this.address1;
    }

    public void setAddress2( String address2 )
    {
        this.address2 = address2;
    }

    public String getAddress2()
    {
        return this.address2;
    }

    public void setZipCode( Integer zipCode )
    {
        this.zipCode = zipCode;
    }

    public Integer getZipCode()
    {
        return this.zipCode;
    }

    public void setCity( String city )
    {
        this.city = city;
    }

    public String getCity()
    {
        return this.city;
    }

    public void setPhone( String phone )
    {
        this.phone = phone;
    }

    public String getPhone()
    {
        return this.phone;
    }

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setEmployee( Employee employee )
    {
        this.employee = employee;
    }

    public Employee getEmployee()
    {
        return this.employee;
    }

    @XmlTransient
    public void setListOfBookOrder( List<BookOrder> listOfBookOrder )
    {
        this.listOfBookOrder = listOfBookOrder;
    }

    public List<BookOrder> getListOfBookOrder()
    {
        return this.listOfBookOrder;
    }

    @XmlTransient
    public void setListOfEmployee( List<Employee> listOfEmployee )
    {
        this.listOfEmployee = listOfEmployee;
    }

    public List<Employee> getListOfEmployee()
    {
        return this.listOfEmployee;
    }

    public void setCountry( Country country )
    {
        this.country = country;
    }

    public Country getCountry()
    {
        return this.country;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(name); 
        sb.append( "|" ); 
        sb.append(address1); 
        sb.append( "|" ); 
        sb.append(address2); 
        sb.append( "|" ); 
        sb.append(zipCode); 
        sb.append( "|" ); 
        sb.append(city); 
        sb.append( "|" ); 
        sb.append(phone); 
        sb.append( "|" ); 
        sb.append(email); 
        return sb.toString(); 
    }

}
