/*
 * Created on 22 nov. 2013 ( Time 16:55:26 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.bean;
// This Bean has a basic Primary Key (not composite) 

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "SHOP"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="SHOP", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Shop.query1", query="SELECT x FROM Shop x WHERE  " ),
//  @NamedQuery ( name="Shop.query2", query="SELECT x FROM Shop x WHERE  " )
// } )
public class Shop implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name="CODE", nullable=false, length=3)
    private String code;

    @Column(name="NAME", length=80)
    private String name ;

    @Column(name="ADDRESS_1", length=80)
    private String address1 ;

    @Column(name="ADDRESS_2", length=80)
    private String address2 ;

    @Column(name="ZIP_CODE")
    private Integer zipCode ;

    @Column(name="CITY", length=45)
    private String city ;

    @Column(name="COUNTRY_CODE", nullable=false, length=2)
    private String countryCode ;

    @Column(name="PHONE", length=14)
    private String phone ;

    @Column(name="EMAIL", length=50)
    private String email ;

    @Column(name="EXECUTIVE", length=4)
    private String executive ;

	public String getCode() {
        return code;
    }
 
    public void setCode(String code) {
        this.code = code;
    }

    public void setName( String name )
    {
        this.name = name;
    }

    public String getName()
    {
        return this.name;
    }

    public void setAddress1( String address1 )
    {
        this.address1 = address1;
    }

    public String getAddress1()
    {
        return this.address1;
    }

    public void setAddress2( String address2 )
    {
        this.address2 = address2;
    }

    public String getAddress2()
    {
        return this.address2;
    }

    public void setZipCode( Integer zipCode )
    {
        this.zipCode = zipCode;
    }

    public Integer getZipCode()
    {
        return this.zipCode;
    }

    public void setCity( String city )
    {
        this.city = city;
    }

    public String getCity()
    {
        return this.city;
    }

    public void setCountryCode( String countryCode )
    {
        this.countryCode = countryCode;
    }

    public String getCountryCode()
    {
        return this.countryCode;
    }

    public void setPhone( String phone )
    {
        this.phone = phone;
    }

    public String getPhone()
    {
        return this.phone;
    }

    public void setEmail( String email )
    {
        this.email = email;
    }

    public String getEmail()
    {
        return this.email;
    }

    public void setExecutive( String executive )
    {
        this.executive = executive;
    }

    public String getExecutive()
    {
        return this.executive;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(code); 
        sb.append("|"); 
        sb.append(name); 
        sb.append( "|" ); 
        sb.append(address1); 
        sb.append( "|" ); 
        sb.append(address2); 
        sb.append( "|" ); 
        sb.append(zipCode); 
        sb.append( "|" ); 
        sb.append(city); 
        sb.append( "|" ); 
        sb.append(phone); 
        sb.append( "|" ); 
        sb.append(email); 
        return sb.toString(); 
    }

}
