/*
 * Created on 22 nov. 2013 ( Time 16:55:27 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.bean;
// This Bean has a basic Primary Key (not composite) 

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Persistent class for entity stored in table "SYNOPSIS"
 */
@XmlRootElement  // JAXB annotation for REST Web Services
@XmlAccessorType(XmlAccessType.PROPERTY) // JAXB accessor = getter/setter pair
@Entity
@Table(name="SYNOPSIS", schema="public" )
// Define named queries here
// @NamedQueries ( {
//  @NamedQuery ( name="Synopsis.query1", query="SELECT x FROM Synopsis x WHERE  " ),
//  @NamedQuery ( name="Synopsis.query2", query="SELECT x FROM Synopsis x WHERE  " )
// } )
public class Synopsis implements Serializable
{
    private static final long serialVersionUID = 1L;

    @Id
    @Column(name="BOOK_ID", nullable=false)
    private Integer bookId;

    @Column(name="SYNOPSIS")
    private String synopsis ;

	public Integer getBookId() {
        return bookId;
    }
 
    public void setBookId(Integer bookId) {
        this.bookId = bookId;
    }

    public void setSynopsis( String synopsis )
    {
        this.synopsis = synopsis;
    }

    public String getSynopsis()
    {
        return this.synopsis;
    }

    public String toString()
    {
        StringBuffer sb = new StringBuffer(); 
        sb.append(bookId); 
        sb.append("|"); 
        return sb.toString(); 
		// synopsis is not in toString because it's a "long text" field
    }

}
