
/*
 * Created on 22 nov. 2013 ( Time 16:27:32 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Author ;
import org.telosys.starterkits.mock.tool.MockValues;

public class AuthorMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Author createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Author createInstance( int id ) {
		Author entity = new Author();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setFirstName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(40) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfBook( TODO ) ; // List<Book> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Author> createList(int count) {
		List<Author> list = new LinkedList<Author>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
