
/*
 * Created on 22 nov. 2013 ( Time 16:27:33 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Badge ;
import org.telosys.starterkits.mock.tool.MockValues;

public class BadgeMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Badge createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Badge createInstance( int badgeNumber ) {
		Badge entity = new Badge();
		// Init Primary Key fields
		entity.setBadgeNumber( badgeNumber) ;
		// Init Data fields
		entity.setAuthorizationLevel( mockValues.nextShort() ) ; // short 
		entity.setEndOfValidity( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfEmployee( TODO ) ; // List<Employee> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Badge> createList(int count) {
		List<Badge> list = new LinkedList<Badge>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
