
/*
 * Created on 22 nov. 2013 ( Time 16:27:38 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.BookOrder ;
import org.telosys.starterkits.mock.tool.MockValues;

public class BookOrderMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public BookOrder createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public BookOrder createInstance( int id ) {
		BookOrder entity = new BookOrder();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setDate( mockValues.nextDate() ) ; // java.util.Date 
		entity.setState( mockValues.nextInteger() ) ; // java.lang.Integer 
		// Init Link fields (if any)
		// setShop( TODO ) ; // Shop 
		// setEmployee( TODO ) ; // Employee 
		// setCustomer( TODO ) ; // Customer 
		// setListOfBookOrderItem( TODO ) ; // List<BookOrderItem> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<BookOrder> createList(int count) {
		List<BookOrder> list = new LinkedList<BookOrder>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
