
/*
 * Created on 22 nov. 2013 ( Time 16:27:42 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Country ;
import org.telosys.starterkits.mock.tool.MockValues;

public class CountryMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Country createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(2) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Country createInstance( String code ) {
		Country entity = new Country();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfCustomer( TODO ) ; // List<Customer> 
		// setListOfPublisher( TODO ) ; // List<Publisher> 
		// setListOfShop( TODO ) ; // List<Shop> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Country> createList(int count) {
		List<Country> list = new LinkedList<Country>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
