
/*
 * Created on 22 nov. 2013 ( Time 16:27:44 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Customer ;
import org.telosys.starterkits.mock.tool.MockValues;

public class CustomerMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Customer createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(5) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Customer createInstance( String code ) {
		Customer entity = new Customer();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setFirstName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setLogin( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setPassword( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setAge( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setCity( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setZipCode( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPhone( mockValues.nextString(20) ) ; // java.lang.String 
		entity.setReviewer( mockValues.nextShort() ) ; // java.lang.Short 
		// Init Link fields (if any)
		// setListOfReview( TODO ) ; // List<Review> 
		// setListOfBookOrder( TODO ) ; // List<BookOrder> 
		// setCountry( TODO ) ; // Country 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Customer> createList(int count) {
		List<Customer> list = new LinkedList<Customer>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
