
/*
 * Created on 22 nov. 2013 ( Time 16:27:47 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Employee ;
import org.telosys.starterkits.mock.tool.MockValues;

public class EmployeeMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Employee createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextString(4) );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Employee createInstance( String code ) {
		Employee entity = new Employee();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setFirstName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setLastName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setManager( mockValues.nextShort() ) ; // java.lang.Short 
		entity.setEmail( mockValues.nextString(320) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfShop( TODO ) ; // List<Shop> 
		// setShop( TODO ) ; // Shop 
		// setListOfWorkgroup( TODO ) ; // List<Workgroup> 
		// setListOfBookOrder( TODO ) ; // List<BookOrder> 
		// setBadge( TODO ) ; // Badge 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Employee> createList(int count) {
		List<Employee> list = new LinkedList<Employee>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
