
/*
 * Created on 22 nov. 2013 ( Time 16:27:51 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Publisher ;
import org.telosys.starterkits.mock.tool.MockValues;

public class PublisherMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Publisher createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Publisher createInstance( int code ) {
		Publisher entity = new Publisher();
		// Init Primary Key fields
		entity.setCode( code) ;
		// Init Data fields
		entity.setName( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setEmail( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setContact( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setCity( mockValues.nextString(45) ) ; // java.lang.String 
		entity.setZipCode( mockValues.nextInteger() ) ; // java.lang.Integer 
		entity.setPhone( mockValues.nextString(14) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setListOfBook( TODO ) ; // List<Book> 
		// setCountry( TODO ) ; // Country 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Publisher> createList(int count) {
		List<Publisher> list = new LinkedList<Publisher>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
