
/*
 * Created on 22 nov. 2013 ( Time 16:27:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Synopsis ;
import org.telosys.starterkits.mock.tool.MockValues;

public class SynopsisMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Synopsis createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextInteger() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Synopsis createInstance( int bookId ) {
		Synopsis entity = new Synopsis();
		// Init Primary Key fields
		entity.setBookId( bookId) ;
		// Init Data fields
		entity.setSynopsis( mockValues.nextString(32700) ) ; // java.lang.String 
		// Init Link fields (if any)
		// setBook( TODO ) ; // Book 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Synopsis> createList(int count) {
		List<Synopsis> list = new LinkedList<Synopsis>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
