
/*
 * Created on 22 nov. 2013 ( Time 16:27:56 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.mock;

import java.util.LinkedList;
import java.util.List;

import org.telosys.starterkits.bean.Workgroup ;
import org.telosys.starterkits.mock.tool.MockValues;

public class WorkgroupMock {

	private MockValues mockValues = new MockValues();
	
	/**
	 * Creates an instance with random Primary Key
	 * @return
	 */
	public Workgroup createInstance() {
		// Primary Key values

		return createInstance( mockValues.nextShort() );
	}
	
	/**
	 * Creates an instance with a specific Primary Key
	 * @param id1
	 * @return
	 */
	public Workgroup createInstance( short id ) {
		Workgroup entity = new Workgroup();
		// Init Primary Key fields
		entity.setId( id) ;
		// Init Data fields
		entity.setName( mockValues.nextString(40) ) ; // java.lang.String 
		entity.setDescription( mockValues.nextString(600) ) ; // java.lang.String 
		entity.setCreationDate( mockValues.nextDate() ) ; // java.util.Date 
		// Init Link fields (if any)
		// setListOfEmployee( TODO ) ; // List<Employee> 
		return entity ;
	}
	
	/**
	 * Creates a list of instances
	 * @param count number of instances to be created
	 * @return
	 */
	public List<Workgroup> createList(int count) {
		List<Workgroup> list = new LinkedList<Workgroup>();		
		for ( int i = 1 ; i <= count ; i++ ) {
			list.add( createInstance() );
		}
		return list;
	}
}
