/*
 * Created on 21 nov. 2013 ( Time 15:35:37 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.test.persistence;


import org.telosys.starterkits.bean.Country ;
import org.telosys.starterkits.mock.CountryMock;
import org.telosys.starterkits.persistence.PersistenceServiceProvider;
import org.telosys.starterkits.persistence.services.CountryPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Country persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class CountryPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Country persistence : delete + load ..." );
		
		CountryPersistence service = PersistenceServiceProvider.getService(CountryPersistence.class);
		
		CountryMock mock = new CountryMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(CountryPersistence service, CountryMock mock, String code ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Country entity = service.load( code );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( code ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( code );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
