/*
 * Created on 22 nov. 2013 ( Time 16:27:45 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.test.persistence;


import org.telosys.starterkits.bean.Customer ;
import org.telosys.starterkits.mock.CustomerMock;
import org.telosys.starterkits.persistence.PersistenceServiceProvider;
import org.telosys.starterkits.persistence.services.CustomerPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Customer persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class CustomerPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Customer persistence : delete + load ..." );
		
		CustomerPersistence service = PersistenceServiceProvider.getService(CustomerPersistence.class);
		
		CustomerMock mock = new CustomerMock();
		
		// TODO : set primary key values here 
		process( service, mock, "A"  );
		// process( service, mock, ... );
	}

	private void process(CustomerPersistence service, CustomerMock mock, String code ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Customer entity = service.load( code );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( code ) ;
			Assert.assertNotNull(entity);

			// This entity references the following entities : 
			// . Country
			/* Insert only if references are OK
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );
			*/

			System.out.println(" . delete : " );
			boolean deleted = service.delete( code );
			System.out.println("   deleted = " + deleted);
		}		
	}
}
