/*
 * Created on 22 nov. 2013 ( Time 16:27:57 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.test.persistence;


import org.telosys.starterkits.bean.Workgroup ;
import org.telosys.starterkits.mock.WorkgroupMock;
import org.telosys.starterkits.persistence.PersistenceServiceProvider;
import org.telosys.starterkits.persistence.services.WorkgroupPersistence;

import org.junit.Assert;
import org.junit.Test;

/**
 * JUnit test case for Workgroup persistence service
 * 
 * @author Telosys Tools Generator
 *
 */
public class WorkgroupPersistenceTest 
{
	@Test
	public void test1() {
		
		System.out.println("Test Workgroup persistence : delete + load ..." );
		
		WorkgroupPersistence service = PersistenceServiceProvider.getService(WorkgroupPersistence.class);
		
		WorkgroupMock mock = new WorkgroupMock();
		
		// TODO : set primary key values here 
		process( service, mock, (short)0  );
		// process( service, mock, ... );
	}

	private void process(WorkgroupPersistence service, WorkgroupMock mock, short id ) {
		System.out.println("----- "  );
		System.out.println(" . load : " );
		Workgroup entity = service.load( id );
		if ( entity != null ) {
			// Found 
			System.out.println("   FOUND : " + entity );
			
			// Save (update) with the same values to avoid database integrity errors  
			System.out.println(" . save : " + entity );
			service.save(entity);
			System.out.println("   saved : " + entity );
		}
		else {
			// Not found 
			System.out.println("   NOT FOUND" );
			// Create a new instance 
			entity = mock.createInstance( id ) ;
			Assert.assertNotNull(entity);

			// No reference : insert is possible 
			// Try to insert the new instance
			System.out.println(" . insert : " + entity );
			service.insert(entity);
			System.out.println("   inserted : " + entity );

			System.out.println(" . delete : " );
			boolean deleted = service.delete( id );
			System.out.println("   deleted = " + deleted);
			Assert.assertTrue(deleted) ;
		}		
	}
}
