/*
 * Created on 22 nov. 2013 ( Time 16:27:57 )
 * Generated by Telosys Tools Generator ( version 2.0.6 )
 */
package org.telosys.starterkits.persistence.services.fake;

import java.util.List;
import java.util.Map;

import org.telosys.starterkits.bean.Workgroup ;
import org.telosys.starterkits.persistence.commons.fake.GenericFakeService;
import org.telosys.starterkits.persistence.services.WorkgroupPersistence;

/**
 * Fake persistence service implementation ( entity "Workgroup" )
 *
 * @author Telosys Tools Generator
 */
public class WorkgroupPersistenceFAKE extends GenericFakeService<Workgroup> implements WorkgroupPersistence {

	public WorkgroupPersistenceFAKE () {
		super(Workgroup.class);
	}
	
	protected Workgroup buildEntity(int index) {
		Workgroup entity = new Workgroup();
		// Init fields with mock values
		entity.setId( nextShort() ) ;
		entity.setName( nextString() ) ;
		entity.setDescription( nextString() ) ;
		entity.setCreationDate( nextDate() ) ;
		return entity ;
	}
	
	
	public boolean delete(Workgroup entity) {
		log("delete ( Workgroup : " + entity + ")" ) ;
		return true;
	}

	public boolean delete( short id ) {
		log("delete ( PK )") ;
		return true;
	}

	public void insert(Workgroup entity) {
		log("insert ( Workgroup : " + entity + ")" ) ;
	}

	public Workgroup load( short id ) {
		log("load ( PK )") ;
		return buildEntity(1) ; 
	}

	public List<Workgroup> loadAll() {
		log("loadAll()") ;
		return buildList(40) ;
	}

	public List<Workgroup> loadByNamedQuery(String queryName) {
		log("loadByNamedQuery ( '" + queryName + "' )") ;
		return buildList(20) ;
	}

	public List<Workgroup> loadByNamedQuery(String queryName, Map<String, Object> queryParameters) {
		log("loadByNamedQuery ( '" + queryName + "', parameters )") ;
		return buildList(10) ;
	}

	public Workgroup save(Workgroup entity) {
		log("insert ( Workgroup : " + entity + ")" ) ;
		return entity;
	}

	public List<Workgroup> search(Map<String, Object> criteria) {
		log("search (criteria)" ) ;
		return buildList(15) ;
	}

}
